name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test tests --verbosity=2 > test_output.txt
    - name: Save test output
      uses: actions/upload-artifact@v2
      with:
        name: test_output.txt
        path: test_output.txt
    - name: Generate Test Coverage HTML
      run: |
        coverage run --source=file_upload,user_profile,user_registration,webpages manage.py test tests
        coverage html
    - name: Save test coverage output
      uses: actions/upload-artifact@v2
      with:
        name: test_coverage.html
        path: htmlcov/index.html
    - name: Push Artifacts to Repo
      run: |
        git add test_output.txt
        git add test_coverage.html
        git commit -m "CI: Add test output and coverage"
        git push

